// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart'
    show Firebase, FirebaseOptions;
import 'package:flutter/cupertino.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo2vMBa8r3TfNjr5h0YXT0SQZ-pNziL-Q',
    appId: '1:790535948484:web:e337fa5cc5f5bb1ba1e191',
    messagingSenderId: '790535948484',
    projectId: 'flash-chat-e3f1f',
    authDomain: 'flash-chat-e3f1f.firebaseapp.com',
    storageBucket: 'flash-chat-e3f1f.appspot.com',
    measurementId: 'G-6JPXD9KSX4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB56s-O4-XxDs4AIDSl_0dXA-sPq-6yRsI',
    appId: '1:790535948484:android:7f015723e3163151a1e191',
    messagingSenderId: '790535948484',
    projectId: 'flash-chat-e3f1f',
    storageBucket: 'flash-chat-e3f1f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAm1cVnwL8pkf8VyxDW9Z_6dEspH7O2SU8',
    appId: '1:790535948484:ios:36dc33be113af30fa1e191',
    messagingSenderId: '790535948484',
    projectId: 'flash-chat-e3f1f',
    storageBucket: 'flash-chat-e3f1f.appspot.com',
    iosBundleId: 'com.dshreddy.flashChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAm1cVnwL8pkf8VyxDW9Z_6dEspH7O2SU8',
    appId: '1:790535948484:ios:e9416415fb06c471a1e191',
    messagingSenderId: '790535948484',
    projectId: 'flash-chat-e3f1f',
    storageBucket: 'flash-chat-e3f1f.appspot.com',
    iosBundleId: 'com.example.flashChat.RunnerTests',
  );
}
